### ISSUE TITLE
REST sevices crabpy

### ISSUE THREAD

**Issue by maarten-vermeyen** [OnroerendErfgoed/crabpy#45]
@koenedaele 

Apperenly there is a RESTful API for accessing the CAPAKEY data: http://geo.agiv.be/capakey/api/v0/Help

example: http://geo.agiv.be/capakey/api/v0/Municipality/44021?type=json

This might solve some performace issues and also returns the actual geometry. I'll try to find out whether this is stable.

**Comment by koenedaele** [comment]
The API is fairly stable, but there's no guarantee they will keep on supporting it. The basic idea would be to implement a CapakeyRestGateway that has the same API as the CapakeyGateway, but doesn't use the SOAP service, but the REST services. I haven't studies the REST service in detail, so I'm not a 100% sure it can be done. But the difference should be minimal. Ideally, we would use the REST service and if they ever shut it down, we could fall back on the SOAP service.

**Comment by koenedaele** [comment]
@BartSaelen Feel free to pass on to someone else if needed.

**Comment by cahytinne** [comment]
Currently, using the `CapakeyRestGateway` (
instead of the SOAP `CapakeyGateway`) will result in a bit of loss of information in terms of parcels. A parcel will be missing two attributes: `cashkey` and `capatype`.

Description of two Cadmap attributes:

> ATTRIBUUT 3 Sleutel planblad
veldnaam CASHKEY
definitie Tekst (12)
soort Beschrijvend, verplicht
omschrijving Sleutel van het planblad waartoe het Capa-exemplaar behoort.
Deze sleutel is genoteerd als vast formaat en is een concatenatie van het
afdelingsnummer, de sectiecode en de planbladcode.
De planbladsleutel is als volgt opgebouwd:
11111A223345
 11111 (5 posities): numerische code kadastrale afdeling (cijfers)
 A (1 positie): Kadastrale sectie (hoofdletter)
 22 (2 posities): identificatie van het planblad, bij enig planblad twee nullen (cijfers)
 33 (2 posities): deel van een planblad (cijfers)
 4 (1 positie): opsplitsing van een kadasterplan in deelblokken (cijfer)
 5 (1 positie): kwalificatie van het digitale plan (cijfer), er zijn 3 mogelijkheden:
o 0 = niet hermeten
o 1 = hermeten analoog
o 2 = hermeten digitaal
De planbladen met de hoogste nauwkeurigheid hebben achteraan de code “2”.
voorbeeld 38018A010001

> ATTRIBUUT 5 Type perceel
veldnaam CAPATY
definitie Tekst (2)
soort Beschrijvend, verplicht
omschrijving Een perceel kan tot 1 van volgende types behoren:
 PR: Privatief perceel
 PP: Perceel openbaar domein of onbepaald domein (wordt opgenomen in entiteit
Caer)
 ER: Foutief perceel (zonder perceelsnummer) (perceel wordt opgenomen in entiteit
Caer)
 XX: Geen informatie (perceel wordt opgenomen in entiteit Caer)

**Comment by koenedaele** [comment]
@cahytinne It looks like they're no longer providing that information, so nothing we can do about it. Don't think we ever used it anyway, so no big deal.

**Comment by cahytinne** [comment]
Is it ok to remove the "beta" from the url? Looks like "https://geoservices.informatievlaanderen.be/capakey/api/v0.1/municipality" is working.
https://github.com/OnroerendErfgoed/crabpy/blob/45_capakey_rest_services/crabpy/gateway/capakey.py#L466

**Comment by koenedaele** [comment]
I think so. I believe they were going to go live at the beginning of april.
